language: objective-c
before_install:
    - brew update
    - brew install xctool
script: xctool -workspace Floc-Commands.xcworkspace -scheme Tests -sdk iphonesimulator -configuration Debug clean build test
